### ISSUE TITLE
broadcast

### ISSUE THREAD

**Issue by gabrielsilvavieira** [funkemunky/Kauri#69]
As mentioned in the comment, the broadcast should be disabled by putting "none" but it sends the message none in the chat

```yml
punishments:
  commands: []
  broadcast: "none"
  bungeeCommand: false
  bypassPerm: true
  bungeeBroadcast: false
  releaseStageMinimum: Release
```

```yml
  # Configure the commands to be run. They will be run in sequential order.
  # Placeholders: %name% (player name)
  commands: []
    # - minecraft:kick %player% Unfair Advantage
  # You can set the broadcast string to "none" to disable punishment broadcasting.
  # Placeholders: %name% (player name)
  broadcast: "none"
  # Send the punishment commands to the bungee. Requires AtlasBungee for this feature to function.
  bungeeCommand: false
  # Allows kauri.bypass.ban permission to function
  bypassPerm: true
  # Broadcast the punishment across your servers. Requires AtlasBungee for this feature to function.
  bungeeBroadcast: false
```

**Comment by gabrielsilvavieira** [comment]
There is also a problem of not saving/generating the comments present in the default config.yml, when creating the Kauri config folders

```yml
  # Configure the commands to be run. They will be run in sequential order.
  # Placeholders: %name% (player name)
  commands: []
    # - minecraft:kick %player% Unfair Advantage
  # You can set the broadcast string to "none" to disable punishment broadcasting.
  # Placeholders: %name% (player name)
  broadcast: "none"
  # Send the punishment commands to the bungee. Requires AtlasBungee for this feature to function.
  bungeeCommand: false
  # Allows kauri.bypass.ban permission to function
  bypassPerm: true
  # Broadcast the punishment across your servers. Requires AtlasBungee for this feature to function.
  bungeeBroadcast: false
```
